### ISSUE TITLE
msg to short 1

### ISSUE THREAD

**Issue by Velociraptor85** [thpe/rklogger#1]
Seit dem letzten git pull bekomme ich nur mehr folgende Meldung.

"[EE] ComLynx::Protocol::get_msg_frame: msg to short 1"

Bin mir nicht wirklich sicher woran das liegen kann.
Mit Debugoutput sieht das ganze so aus.

"
root@server:~/rklogger/src/bin# ./rklogger e7 df
7E FF  3  0  1 E7 DF  0 15 3F B3 7E 12 bytes written
 0  read 1 bytes
root@server:~/rklogger/src/bin# ./rklogger e7 df 1 1 1
7E FF  3  0  1 E7 DF  A  1 C8  1 D0  1  1 80  0  0  0  0 E0 BE 7E 22 bytes written
 0  read 1 bytes
[EE] ComLynx::Protocol::get_msg_frame: msg to short 1
U
"

**Comment by Velociraptor85** [comment]
Also dieses Problem ist immer noch vorhanden zwar umgehe ich es indem ich einfach öfter hinterineander nachfrage aber ich denke das hier leider irgendwo ein problem ist leider bin ich mir nicht ganz sicher wie man auf den fehler kommen kann aber gut der workaround funktioniert halbwegs

**Comment by thpe** [comment]
Ich vermute das ist der Adapter der gesendete Zeichen wieder zurueck sendet. Leider habe ich keinen zum testen.
