### ISSUE TITLE
compile on never rasppi

### ISSUE THREAD

**Issue by affer** [thpe/rklogger#4]
during compiling on rasppi 2 with never install the following error is occuring:

~/rklogger/build $ make
[100%] Built target lib_rklogger
[100%] Built target rklogger
/bin/sh: 1: cannot create man/rklogger.1.gz: Directory nonexistent
doc/CMakeFiles/rklogger_man.dir/build.make:57: recipe for target 'rklogger_man' failed
make[2]: *** [rklogger_man] Error 2
CMakeFiles/Makefile2:197: recipe for target 'doc/CMakeFiles/rklogger_man.dir/all' failed
make[1]: *** [doc/CMakeFiles/rklogger_man.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

can the code be updated to be able to compile on newer system.

thanks

**Comment by thpe** [comment]
can you provide more information? Is this is clean checkout?
I just tried on a Raspberry Pi 2 and it works.

**Comment by affer** [comment]
hi thomas.. here is the output:

i may be doing something wrong, the same happens on a pi i do the compiling without sudo on.

thanks for your reply. i have also added the output on your github. i am very glad for your program by the way.. it is rock solid :-)

kind regards

Rasmus
Denmark

affer@raspberrypi:~ $ mkdir build
affer@raspberrypi:~ $ cd ..
affer@raspberrypi:/home $ git clone https://github.com/thpe/rklogger.git
fatal: could not create work tree dir 'rklogger': Permission denied
affer@raspberrypi:/home $ sudo git clone https://github.com/thpe/rklogger.git
Cloning into 'rklogger'...
remote: Enumerating objects: 270, done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270
Receiving objects: 100% (270/270), 54.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (159/159), done.
affer@raspberrypi:/home $ cd rklogger/
affer@raspberrypi:/home/rklogger $ ls
CMakeLists.txt  COPYING  README  doc  lib  script  src
affer@raspberrypi:/home/rklogger $ mkdir build
mkdir: cannot create directory 'build': Permission denied
affer@raspberrypi:/home/rklogger $ sudo mkdir build
affer@raspberrypi:/home/rklogger $ cd build/
affer@raspberrypi:/home/rklogger/build $ sudo cmake ..
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rklogger/build
affer@raspberrypi:/home/rklogger/build $ sudo make
Scanning dependencies of target lib_rklogger
[ 16%] Building CXX object lib/CMakeFiles/lib_rklogger.dir/serialport.C.o
[ 33%] Building CXX object lib/CMakeFiles/lib_rklogger.dir/logger.C.o
[ 50%] Building CXX object lib/CMakeFiles/lib_rklogger.dir/protocol_comlynx.C.o
[ 66%] Linking CXX static library liblib_rklogger.a
[ 66%] Built target lib_rklogger
Scanning dependencies of target rklogger
[ 83%] Building CXX object src/CMakeFiles/rklogger.dir/main.C.o
[100%] Linking CXX executable rklogger
[100%] Built target rklogger
Scanning dependencies of target rklogger_man
/bin/sh: 1: cannot create man/rklogger.1.gz: Directory nonexistent
doc/CMakeFiles/rklogger_man.dir/build.make:57: recipe for target 'rklogger_man' failed
make[2]: *** [rklogger_man] Error 2
CMakeFiles/Makefile2:197: recipe for target 'doc/CMakeFiles/rklogger_man.dir/all' failed
make[1]: *** [doc/CMakeFiles/rklogger_man.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by thpe** [comment]
Yes, wrong order, first clone, then you change into the directory, then follow the introductions

`git clone https://github.com/thpe/rklogger.git
cd rklogger
mkdir build
cd build
cmake ..
make
make install`

**Comment by thpe** [comment]
I could reproduce the error here in the CI and I made a fix, could you try? Please use the installation instructions above, _only_ the `make install` step should require `sudo` in case you have insufficient permission.

**Comment by affer** [comment]
Working perfectly on my rp4 with latest raspian.

Thanks for the help.

i am logging perfectly to pvoutput now.. only 1 hickup is with webserver enabled.. it wont run.. but that is ofcause not your program,

perl danfoss.pl 
Can't locate web-server.pl in @INC (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/arm-linux-gnueabihf/perl5/5.28 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at danfoss.pl line 183.

Thanks again!

kind regards

**Comment by affer** [comment]
nevermind i found out.. export PERL5LIB=/home/pi/danfoss

thanks again.

**Comment by thpe** [comment]
Thank you for your feedback!
